### ISSUE TITLE
More like a request

### ISSUE THREAD

**Issue by nortont** [kloon/woocommerce-sold-out-products#1]
I came across your plugin while searching for away to mark items as discontinued.
Currently WooCommerce only offers the option of out of stock, meaning people ask when it will be in stock.
I don't want to delete my discontinued products as they have SEO value and will result in 404 errors.

Is it possible your plugin could have an option to do this for any product without the widgit. Just in the normal shop layout based on the selection in the "In Stock" menu

![image](https://f.cloud.github.com/assets/4540401/1521766/4dbd78b6-4b9a-11e3-8e3f-bb4311747f5a.png)

**Comment by kloon** [comment]
@nortont the easiest way would be to just rename the badge from out of stock to discontinued, you can do this by adding the following code to your theme's functions.php file

``` php
add_filter( 'woocommerce_sold_out_flash', 'wc_change_sold_out_flash_text' );
function wc_change_sold_out_flash_text( $text ) {
    return __( 'Discontinued', 'wc-sold-out-products' );
}
```

The extension already adds the text to products on the archive pages automatically if you are running the latest version.

**Comment by chirag-v** [comment]
@kloon What if some products in store are out of stock and few are discontinued. Simply renaming won't address the problem this way.

I am in for WooIdea: http://ideas.woothemes.com/forums/133476-woocommerce/suggestions/3778491-discontinued-products-option-under-inventory-sto

**Comment by kloon** [comment]
@chirag-v the extension was not designed to work with different types, so no it will not work with 2 different types like sold out and discontinued.
